day02/myProject/myApp/urls.py
from django.urls import path
from .views import home, profile, list_item, retrive_item, list_category, retrive_category, delete_category

app_name = "myApp"

urlpatterns = [
    path('', home, name='home'),
    path('profile', profile, name='profile'),
    path('category', list_category, name='list-category'),
    path('category/<int:pk>/', retrive_category, name='retrive-category'),
    path('category/delete/<int:pk>/', delete_category, name='delete-category'),
    path('item', list_item, name='list-item'),
    path('item/<int:pk>/', retrive_item, name='retrive-item')
    
]

day02/myProject/myProject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myApp.urls'))
]

day02/myProject/myApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    is_use = models.BooleanField(default=True)
    
    def __str__(self) -> str:
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=300)
    cateogy = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_use = models.BooleanField(default=True)
    
    def __str__(self) -> str:
        return self.name

class Stock(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    price = models.PositiveSmallIntegerField()
    amount = models.PositiveSmallIntegerField()
    is_use = models.BooleanField(default=True)
    
    def __str__(self) -> str:
        return self.item.name

class Transaction(models.Model):
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.PositiveSmallIntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

day02/myProject/myApp/views.py
from django.shortcuts import render, redirect
from .models import Category, Item

# Create your views here.
def home(request):
    return render(request, 'myApp/home.html')

def profile(request):
    return render(request, 'myApp/profile.html')

def list_category(request):
    if request.method == "POST":
        data = request.POST
        Category.objects.create(
            name = data['name']
        )
    categoys = Category.objects.filter(is_use=True)
    context = {
        'categorys': categoys
    }
    return render(request=request, template_name='myApp/category-list.html', context=context)

def retrive_category(request, pk):
    category = Category.objects.get(id=pk)
    if request.method == "POST":
        data = request.POST
        category.name = data['name']
        category.save()
    context = {
        'category': category
    }
    return render(request=request, template_name='myApp/category-retrive.html', context=context)

def delete_category(request, pk):
    catrgory = Category.objects.get(id=pk)
    catrgory.is_use=False
    catrgory.save()
    return redirect('myApp:list-category')
    

def list_item(request):
    context = {
        'items': Item.objects.filter(is_use=True),
        'categorys': Category.objects.filter(is_use=True)
    }
    return render(request=request, template_name='myApp/item-list.html', context=context)

def retrive_item(request, pk):
    item = Item.objects.get(id=pk)
    context = {
        'item': item
    }
    return render(request=request, template_name='myApp/item-retrive.html', context=context)

day02/myProject/myApp/templates/myApp/category-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item</title>
</head>
<body>
    <div>
        <h1>Category</h1>
        <table>
            <tr>
                <tr>
                    <th> id </th>
                    <th> name </th>
                </tr>
            </tr>
            {% for category in categorys %}
                <tr>
                    <td> <a href="{% url 'myApp:retrive-category' category.id %}">{{category.id}}</a> </td>
                    <td> {{category.id}} </td>
                    <td>{{category.name}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <br>
    <div>
        <h2>Create Category</h2>
        <form method="post">
            {% csrf_token %}
            <input type="text" name="name" required>
            <button type="submit">SAVE</button>
        </form>
    </div>
</body>
<style>
    table, th, td {
      border:1px solid black;
    }
</style>
</html>

day02/myProject/myApp/templates/myApp/category-retrive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item</title>
</head>
<body>
    <div>
        <h1>Category</h1>
        <table>
            <tr>
                <tr>
                    <th> id </th>
                    <th> name </th>
                </tr>
            </tr>
            <form method="post">
                <tr>
                    {% csrf_token %}
                    <td>
                        <input id="id" type="number" value="{{category.id}}" disabled>
                    </td>
                    <td>
                        <input id="name" type="text" name="name" value="{{category.name}}" required>
                    </td>
                    <td>
                        <button><a href="{% url 'myApp:delete-category' category.id %}">DELETE</a></button>
                    </td>
                    
                </tr>
                <tr>
                    <td>
                        <button type="submit">SAVE</button>
                    </td>
                </tr>
            </form>
        </table>
    </div>
    <br>
    <a href="{% url 'myApp:list-category' %}">ย้อนกลับ</a>
</body>
<style>
    table, th, td {
      border:1px solid black;
    }
</style>
</html>

day02/myProject/myApp/templates/myApp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Hello world</h1>
    <a href="{% url "myApp:list-category" %}">Category</a>
    <br>
    <a href="{% url "myApp:list-item" %}">Item</a>
</body>
</html>

day02/myProject/myApp/templates/myApp/item-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item</title>
</head>
<body>
    <div>
        <h1>ITEMS</h1>
        <table>
            <tr>
                <tr>
                    <th> id </th>
                    <th> name </th>
                </tr>
            </tr>
            {% for item in items %}
                <tr>
                    <td> <a href="{% url 'myApp:retrive-item' item.id %}">{{item.id}}</a> </td>
                    <td>{{item.name}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div>
        <h2>Create Items</h2>
        <form method="post">
            {% csrf_token %}
            <label for="category">category : </label>
            <select name="category" id="category" required>
                {% for category in categorys %}
                    <option value="{{category.id}}">{{category.name}}</option>
                {% endfor %}
            </select>
            <br>
            <label for="category">name : </label>
            <input type="text" name="name" required>
            <br>
            <button type="submit">SAVE</button>
        </form>
    </div>
</body>
<style>
    table, th, td {
      border:1px solid black;
    }
</style>
</html>

day02/myProject/myApp/templates/myApp/item-retrive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item</title>
</head>
<body>
    <table>
        <tr>
            <tr>
                <th>  <a href=""></a> id </th>
                <th> name </th>
            </tr>
        </tr>
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.name}}</td>
        </tr>
    </table>
</body>
<style>
    table, th, td {
      border:1px solid black;
    }
</style>
</html>

day02/myProject/myApp/templates/myApp/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<body>
    <h1>My name is Sothana</h1>
    <h1>Hello every one</h1>
</body>
</html>